// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using listorize.Model;

#nullable disable

namespace listorize.Migrations
{
    [DbContext(typeof(ListorizeContext))]
    [Migration("20240723155613_ParentListNullable")]
    partial class ParentListNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("listorize.Model.List", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("List");
                });

            modelBuilder.Entity("listorize.Model.ListColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LookupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("LookupId");

                    b.ToTable("ListColumn");
                });

            modelBuilder.Entity("listorize.Model.ListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NoteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("NoteId");

                    b.HasIndex("ParentListId");

                    b.ToTable("ListItem");
                });

            modelBuilder.Entity("listorize.Model.ListValue", b =>
                {
                    b.Property<int>("ListItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ListItemId", "ListColumnId");

                    b.HasIndex("ListColumnId");

                    b.ToTable("ListValue");
                });

            modelBuilder.Entity("listorize.Model.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lookup");
                });

            modelBuilder.Entity("listorize.Model.LookupOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LookupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LookupId");

                    b.ToTable("LookupOption");
                });

            modelBuilder.Entity("listorize.Model.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("listorize.Model.ListColumn", b =>
                {
                    b.HasOne("listorize.Model.List", "List")
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("listorize.Model.Lookup", "Lookup")
                        .WithMany()
                        .HasForeignKey("LookupId");

                    b.Navigation("List");

                    b.Navigation("Lookup");
                });

            modelBuilder.Entity("listorize.Model.ListItem", b =>
                {
                    b.HasOne("listorize.Model.List", "List")
                        .WithMany()
                        .HasForeignKey("ListId");

                    b.HasOne("listorize.Model.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId");

                    b.HasOne("listorize.Model.List", "ParentList")
                        .WithMany()
                        .HasForeignKey("ParentListId");

                    b.Navigation("List");

                    b.Navigation("Note");

                    b.Navigation("ParentList");
                });

            modelBuilder.Entity("listorize.Model.ListValue", b =>
                {
                    b.HasOne("listorize.Model.ListColumn", "ListColumn")
                        .WithMany()
                        .HasForeignKey("ListColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("listorize.Model.ListItem", "ListItem")
                        .WithMany()
                        .HasForeignKey("ListItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListColumn");

                    b.Navigation("ListItem");
                });

            modelBuilder.Entity("listorize.Model.LookupOption", b =>
                {
                    b.HasOne("listorize.Model.Lookup", "Lookup")
                        .WithMany()
                        .HasForeignKey("LookupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lookup");
                });
#pragma warning restore 612, 618
        }
    }
}
